---
- name: Install bash_it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: "{{ ansible_env['HOME'] }}/.bash_it"
    version: master
  tags: ["bash"]

- name: Configure bash_it
  blockinfile:
    path: "{{ ansible_env['HOME'] }}/.bashrc_{{ ansible_env['USER'] }}"
    insertafter: EOF
    marker_begin: bash_it
    block: |
      # If not running interactively, don't do anything
      case $- in
        *i*) ;;
          *) return;;
      esac

      export BASH_IT="/home/{{ ansible_env['USER'] }}/.bash_it"
      #export BASH_IT_THEME='modern'
      export BASH_IT_THEME='powerline'
      unset MAILCHECK
      export SCM_CHECK=true
      source "$BASH_IT"/bash_it.sh
  tags: ["bash"]

- name: Copy .inputrc
  copy:
    src: inputrc
    dest: "{{ ansible_env['HOME'] }}/.inputrc"
  tags: ["bash"]

- name: Configure bash_it plugins
  shell: |
    source "{{ ansible_env['HOME'] }}/.bash_it/bash_it.sh"
    bash-it enable {{ item.command }}
  args:
    creates: /home/{{ ansible_env['USER'] }}/.bash_it/enabled/{{ item.name }}
    executable: /bin/bash
  loop:
    - {name: "150---general.aliases.bash", command: "alias general"}
    - {name: "150---homebrew.aliases.bash", command: "alias homebrew"}
    - {name: "250---base.plugin.bash", command: "plugin base"}
    - {name: "350---bash-it.completion.bash", command: "completion bash-it"}
    - {name: "350---system.completion.bash", command: "completion system"}
    - {name: "350---terraform.completion.bash", command: "completion terraform"}
    - {name: "365---alias-completion.plugin.bash", command: "plugin alias-completion"}
  tags: ["bash"]